### ISSUE TITLE
Naturedex Repository Deleted

### ISSUE THREAD

**Issue by SealsRock12** [Naturedex/Naturedex-Android#1]
Hello,
I would like an explanation on why the old Naturedex repository was deleted. There _was_ some work done in that repository, the work I did on the `node-server` branch. Thank you.

**Comment by Moogamouth** [comment]
Wait, what? I didn't know, sorry. I deleted it so that we could divide the repos into different platforms. Also, btw, here's a discord link. https://discord.gg/eKqGZnV

**Comment by Moogamouth** [comment]
I literally didn't even notice this issue. I'm very sorry.
